# Generated by Django 2.1.5 on 2022-04-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('bio_text', models.CharField(blank=True, max_length=500, null=True)),
                ('_title', models.CharField(blank=True, choices=[('cstaff', 'Crimson staff writer'), ('contrib', 'Contributing writer'), ('photog', 'Photographer'), ('design', 'Designer'), ('editor', 'Editor'), ('opinion', 'Crimson opinion writer'), ('opinion_contrib', 'Contributing opinion writer'), ('sponsored_contrib', 'Sponsored Contributor')], max_length=70, null=True, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(related_name='content', to='content.Contributor'),
        ),
    ]
