# Generated by Django 2.1.5 on 2022-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
